<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="$(ModRepositoryRoot)shared/ModEngineering/build/Android.props" />
    <PropertyGroup>
        <Version>1.1.7</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>disable</Nullable>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>

    <Import Project="$(ModRepositoryRoot)shared/ModEngineering/build/SharedDependencies.props" />
    <Target Name="CollectExtraPackageFiles" BeforeTargets="GetModPackageFiles">
        <ItemGroup>
            <ModPackageFile
                Include="$(ModRepositoryRoot)dependencies/font/notosanscjktc"
                Destination="UserData/TSKHook/notosanscjktc"
            />
        </ItemGroup>
    </Target>
</Project>
